name: Code & Image Scan with SonarQube and Trivy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          # No need for sonar-token input, the action automatically uses the SONAR_TOKEN secret

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure the SONAR_TOKEN is set as an env variable
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Passing the token here directly

  trivy_scan:
    runs-on: ubuntu-latest
    needs: sonar_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh

      - name: Scan Docker Image with Trivy
        run: |
          docker build -t my-app .
          trivy image --format json --output trivy-report.json my-app

  send_report:
    runs-on: ubuntu-latest
    needs: [sonar_scan, trivy_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send email with scan reports
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 587
          smtp-username: ${{ secrets.EMAIL_USERNAME }}
          smtp-password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_USERNAME }}
          subject: "Code and Image Scan Report"
          body: |
            Hello,

            Here is the report for the recent SonarQube and Trivy scans:

            - SonarQube Report: Please check the SonarQube dashboard for detailed results.
            - Trivy Image Scan Report: See the attached JSON file for detailed findings.

          attachments: trivy-report.json
