name: Docker Image Security Scan with Trivy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh -o install.sh
          chmod +x install.sh
          ./install.sh
          sudo mv ./bin/trivy /usr/local/bin/trivy

      - name: Verify Trivy Installation
        run: |
          echo $PATH
          which trivy
          trivy --version

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Scan Docker Image with Trivy
        run: |
          trivy image --format json --output trivy-report.json my-app

      - name: Format Trivy Report to Readable Format
        run: |
          cat trivy-report.json | jq '.' > trivy-report-readable.txt
          cat trivy-report-readable.txt

      - name: Send Email with Trivy Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Trivy Image Scan Report"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello,

            Please find the readable report of the recent Trivy scan:

            $(cat trivy-report-readable.txt)

          attachments: |
            trivy-report.json
